// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxzsydczuxwhnqnmjiyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4enN5ZGN6dXh3aG5xbm1qaXlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0NzQ1MjUsImV4cCI6MjA5MDA1MDUyNX0.EPJbnS-pyp0ppJuUA0KEB2M8fnZAnhjLyHhDKcHNz8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});